### ISSUE TITLE
按照 Quick Start 操作，编译流程不通过

### ISSUE THREAD

**Issue by Aarebecca** [TuGraph-family/tugraph-analytics#1]
按照 [Quick Start](https://github.com/TuGraph-family/tugraph-analytics/blob/master/docs/docs-cn/quick_start.md) 操作，执行

```bash
mvn clean package -DskipTests
```
后报错：
<img width="868" alt="image" src="https://github.com/TuGraph-family/tugraph-analytics/assets/25787943/eae08e50-d789-4fe9-a9ba-1f651dc5095f">

环境：
Java: 1.8.0_202
Maven: 3.9.2

**Comment by pengzhiwei2018** [comment]
看上去是Java环境的问题，确认JDK是否正确安装，另外，JAVA_HOME环境变量也要配置一下.

**Comment by Leomrlin** [comment]
确认下JDK和MAVEN是否正确安装

**Comment by Leomrlin** [comment]
确认下JDK和MAVEN是否正确安装
`java -version`

**Comment by Aarebecca** [comment]
排查后发现是 mvn 使用了系统默认的 JDK，在 `.zshrc` 中配置 JAVA_HOME 为实际安装JDK路径

如：
<img width="537" alt="image" src="https://github.com/TuGraph-family/tugraph-analytics/assets/25787943/e1064e33-98dc-4a41-bc1f-90e3772fd70c">


后续问题记录：
* 再次尝试编译，提示 `Unable to find javadoc command`
<img width="931" alt="image" src="https://github.com/TuGraph-family/tugraph-analytics/assets/25787943/25548a0d-3650-4449-aad7-61aba27e46dc">

> 在根目录下 `pom.xml` 文件中配置 `maven-javadoc-plugin`
> 添加 `<javadocExecutable>${java.home}/../bin/javadoc</javadocExecutable>`，⚠️ JDK 11 为: `${java.home}/bin/javadoc`
> <img width="513" alt="image" src="https://github.com/TuGraph-family/tugraph-analytics/assets/25787943/72fe452b-a2ef-4964-8ce8-7554e472eff2">

* 尝试编译，提示 `Could not resolve dependencies for project com.antgroup.tugraph`
<img width="843" alt="image" src="https://github.com/TuGraph-family/tugraph-analytics/assets/25787943/ab0796ff-4c66-4044-805b-364606a37986">

**Comment by Leomrlin** [comment]
感谢详细的记录，首次编译可能会比较慢，后面在指引文档里添加maven更换国内源的tips，并引导确认下jdk和maven是否正确安装，再次感谢你的建议！
