### ISSUE TITLE
GeaFlow console connect fail on 8888 port

### ISSUE THREAD

**Issue by aqzwy** [TuGraph-family/tugraph-analytics#10]
# 启动方式
基于quickStart 启动docker本地化部署

# 异常记录
1. 访问http://{部署机器}:8888，使用chrome浏览器
2. 检查network，发现
http://127.0.0.1:8080/auth/login
http://127.0.0.1:8080/api/instances
两个接口报错

# 尝试解决方法
1. 进入容器内部修改application.properties 文件参数geaflow.host为本机地址
2.  重启docker
3. 问题未解决，访问地址依旧为127.0.0.1，无法访问，提示服务器异常

![image](https://github.com/TuGraph-family/tugraph-analytics/assets/18528119/60fb6087-e098-4795-91bc-10aedc612eab)
![image](https://github.com/TuGraph-family/tugraph-analytics/assets/18528119/3607e7f2-f50a-4bb5-bda4-cccd52f9b9cd)

**Comment by pengzhiwei2018** [comment]
@652053395 看一下这个问题吧？

**Comment by 652053395** [comment]
@aqzwy 可以进入容器看一下 /tmp/logs/geaflow/app-defualt.log 和/tmp/logs/geaflow-web/stdout.log这个日志吗

**Comment by 652053395** [comment]
还有/tmp/logs/geaflow/common-error.log

**Comment by Leomrlin** [comment]
本地运行是可以的，在其他机器上部署还有问题正在修复。如果现在要在非本机部署，可以把以下两个文件中的IP地址修改为需要部署机器的IP地址，重新执行 bash ./build.sh --all，并重新执行docker run
./geaflow-web/packages/app/client/src/components/@@plugins/src/components/console/geaflow/constants/index.ts
./geaflow-web/packages/app/client/src/components/@@plugins/src/components/studio/geaflow/constants/index.ts

**Comment by Kwafoor** [comment]
> 本地部署是OK的，但在非本机部署还有问题正在修复。如果现在要在非本机部署，可以把以下两个文件中的IP地址修改为需要部署机器的IP地址，重新执行 bash ./build.sh --all，并重新执行docker run ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/console/geaflow/constants/index.ts ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/studio/geaflow/constants/index.ts
> 
> 非本机部署无需进入容器内部修改application.properties，加your.host.ip参数即可，类似 docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 -e geaflow.host=${your.host.ip} geaflow-console:0.1 参考https://github.com/TuGraph-family/tugraph-analytics/blob/master/docs/docs-cn/deploy/install_guid.md

I encountered the same problem. Should we submit a PR to modify the quick_start_docker.md file and solve the problem?

**Comment by pengzhiwei2018** [comment]
@Kwafoor 这个问题我们在修复中了，是前端模块的一个问题。

**Comment by Leomrlin** [comment]
@Kwafoor 是的，这个问题非本地部署比较容易碰到，前端组件在加载上述两个index.ts文件时错误地使用了默认的值localhost，我们在着手修复了。手动写死一个IP地址暂时可以绕过这个问题。

**Comment by aqzwy** [comment]
@652053395 日志如下
 /tmp/logs/geaflow/app-defualt.log 
[common-error.log](https://github.com/TuGraph-family/tugraph-analytics/files/11754813/common-error.log)

/tmp/logs/geaflow-web/stdout.log
[stdout.log](https://github.com/TuGraph-family/tugraph-analytics/files/11754814/stdout.log)

/tmp/logs/geaflow/common-error.log
[app-default.log](https://github.com/TuGraph-family/tugraph-analytics/files/11754815/app-default.log)

**Comment by 652053395** [comment]
> 本地部署是OK的，但在非本机部署还有问题正在修复。如果现在要在非本机部署，可以把以下两个文件中的IP地址修改为需要部署机器的IP地址，重新执行 bash ./build.sh --all，并重新执行docker run ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/console/geaflow/constants/index.ts ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/studio/geaflow/constants/index.ts
> 
> 非本机部署无需进入容器内部修改application.properties，加your.host.ip参数即可，类似 docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 -e geaflow.host=${your.host.ip} geaflow-console:0.1 参考https://github.com/TuGraph-family/tugraph-analytics/blob/master/docs/docs-cn/deploy/install_guid.md

@aqzwy 部署机器不是本地是吗？
 照着这个重启试下呢 如果还是不行 可以私个联系方式 我加你看看

**Comment by fanzhidongyzby** [comment]
@aqzwy 本地启动目前默认构建的是指向localhost的访问地址，如果指定了远程ip，暂时只能在容器内geaflow-web目录下，kill掉所有node进程，执行yarn build && yarn start 重新编译一下前端才可以。
为了解决该问题，我们准备在容器内启动nginx帮助解决问题。
具体进展关注Issue：[Use Nginx to Proxy 8888 and 8080 Port in Geaflow Console Docker Container](https://github.com/TuGraph-family/tugraph-analytics/issues/18)

**Comment by aqzwy** [comment]
> > 本地部署是OK的，但在非本机部署还有问题正在修复。如果现在要在非本机部署，可以把以下两个文件中的IP地址修改为需要部署机器的IP地址，重新执行 bash ./build.sh --all，并重新执行docker run ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/console/geaflow/constants/index.ts ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/studio/geaflow/constants/index.ts
> > 非本机部署无需进入容器内部修改application.properties，加your.host.ip参数即可，类似 docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 -e geaflow.host=${your.host.ip} geaflow-console:0.1 参考https://github.com/TuGraph-family/tugraph-analytics/blob/master/docs/docs-cn/deploy/install_guid.md
> 
> @aqzwy 部署机器不是本地是吗？ 照着这个重启试下呢 如果还是不行 可以私个联系方式 我加你看看

我是部署在远程服务器，我去尝试下您给我的启动命令看看效果咋样  : )

**Comment by aqzwy** [comment]
> > 本地部署是OK的，但在非本机部署还有问题正在修复。如果现在要在非本机部署，可以把以下两个文件中的IP地址修改为需要部署机器的IP地址，重新执行 bash ./build.sh --all，并重新执行docker run ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/console/geaflow/constants/index.ts ./geaflow-web/packages/app/client/src/components/@@plugins/src/components/studio/geaflow/constants/index.ts
> > 非本机部署无需进入容器内部修改application.properties，加your.host.ip参数即可，类似 docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 -e geaflow.host=${your.host.ip} geaflow-console:0.1 参考https://github.com/TuGraph-family/tugraph-analytics/blob/master/docs/docs-cn/deploy/install_guid.md
> 
> @aqzwy 部署机器不是本地是吗？ 照着这个重启试下呢 如果还是不行 可以私个联系方式 我加你看看

@652053395 我是部署在远程服务器，我去尝试下您给我的启动命令看看效果咋样 : )

**Comment by aqzwy** [comment]
@652053395 18031867231,您方便的话可以私聊，探讨下这问题

**Comment by aqzwy** [comment]
# 解决方案
结合两位大佬人员的回答，操作步骤如下:
1.  以下命令启动容器
`docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 -e geaflow.host=${your.public.ip} -e geaflow.web.gateway.url=http://${your.public.ip}:8080 geaflow-console:0.1`

2. 进入容器杀掉yarn、node相关进程

4. 进入到geaflow-web根目录并重新编译
`cd /opt/geaflow-web
yarn build
`

5. 启动geaflow-web服务
`cd /opt/geaflow-web
yarn start&`

6. 个别情况下需要修改容器geaflow参数
`spring.datasource.url=jdbc:mysql://127.0.0.1:3306/geaflow?useUnicode=true&characterEncoding=utf8`
修改为127.0.0.1

感谢 @652053395    @Leomrlin  两位大佬的帮助

**Comment by pengzhiwei2018** [comment]
This have fix in https://github.com/TuGraph-family/tugraph-analytics/pull/22
