### ISSUE TITLE
jdk安装路径不能有空格

### ISSUE THREAD

**Issue by caixincx** [TuGraph-family/tugraph-analytics#11]
跑quick start的demo时，发现如果jdk路径中有空格会导致脚本执行失败，空格后面的；路径会被截断
![65b443e549b444ef27054ab1cf1deb2](https://github.com/TuGraph-family/tugraph-analytics/assets/37977992/370cfc17-2468-4aa0-87ca-14ae266a478f)

**Comment by pengzhiwei2018** [comment]
@caixincx GeaFlow目前没有适配Windows系统，编译运行需要linux或者mac环境，window系统可以安装linux虚拟机来运行。

**Comment by caixincx** [comment]
> @caixincx GeaFlow目前没有适配Windows系统，编译运行需要linux或者mac环境，window系统可以安装linux虚拟机来运行。

今天我在windows系统上编译成功了，quick start的demo也跑通了

**Comment by caixincx** [comment]
> @caixincx GeaFlow目前没有适配Windows系统，编译运行需要linux或者mac环境，window系统可以安装linux虚拟机来运行。

在windows系统编译的时候可能会出现一些奇奇怪怪的问题

**Comment by pengzhiwei2018** [comment]
@caixincx 厉害啊，适配windows应该要做不少工作吧。
