### ISSUE TITLE
Fix yarn build error when build image for geaflow-web

### ISSUE THREAD

**Issue by baizn** [TuGraph-family/tugraph-analytics#124]
**Describe the bug**

Execute build to report ts compilation errors.

![image](https://github.com/TuGraph-family/tugraph-analytics/assets/9443867/bc5d5094-b331-41bc-8e7e-cf2e1fdab869)

**Expected behavior**
- execute yarn build

**Comment by pengzhiwei2018** [comment]
Fixed in https://github.com/TuGraph-family/tugraph-analytics/pull/123
