### ISSUE TITLE
JDBC connector cannot write data into mysql database

### ISSUE THREAD

**Issue by Leomrlin** [TuGraph-family/tugraph-analytics#158]
**Describe the bug**
 After using the JDBC Connector to connect to MYSQL for writing, the job runs successfully but the data is not written to the database. The reason is that the Sink implementation creates a temporary table, causing the data to be written into the temporary table.

**Expected behavior**

**Additional context**

**Comment by pengzhiwei2018** [comment]
Fixed in https://github.com/TuGraph-family/tugraph-analytics/pull/159
