### ISSUE TITLE
[Future] graph Iteration

### ISSUE THREAD

**Issue by cbqiao** [TuGraph-family/tugraph-analytics#167]
**Is your feature request related to a problem? Please describe.**
图迭代计算中，如果满足迭代收敛或者迭代结束条件，则需要提前结束迭代。
需要新增api支持用户
1. 搜集迭代信息，并支持局部聚合和全局聚合。
2. 支持根据全局聚合值，判断是否提前终止

**Describe alternatives you've considered**
需要实现agg相关算法，以traversal为例，实现`VertexCentricAggTraversal`
和普通traversal(`VertexCentricTraversal`)不一样的是，接口getTraversalFunction返回对应VertexCentricAggTraversalFunction<K, VV, EV, M, R, I, GR>>，该function在普通function基础上多实现接口`VertexCentricAggContextFunction<I, GR>`, 其在traversal期间提供agg context和aggrete接口。
```
public interface VertexCentricAggTraversalFunction<K, VV, EV, M, R, I, GR>
    extends VertexCentricTraversalFunction<K, VV, EV, M, R>, VertexCentricAggContextFunction<I, GR> {
}
```
 同时新增接口getAggregateFunction，该接口定义部分aggregate和全局aggregate具体实现。
```
VertexCentricAggTraversalFunction<K, VV, EV, M, R, I, GR>> getTraversalFunction();
VertexCentricAggregateFunction<I, PA, PR, GA, GR> getAggregateFunction();
```

**Comment by pengzhiwei2018** [comment]
Merged in https://github.com/TuGraph-family/tugraph-analytics/pull/168
