### ISSUE TITLE
Instr/IndexOf support BinaryString as input parameter

### ISSUE THREAD

**Issue by pengzhiwei2018** [TuGraph-family/tugraph-analytics#20]
Currently GeaFlow uses BinaryString as its implementation for string, which provides better performance. However, at present, the built-in String Function uses string as the input parameter, and a direct conversion from BinaryString to String is required in the calculation phase, which has performance overhead. Implement the InStr/IndexOf function with BinaryString as an input.

**Comment by liuxiaocs7** [comment]
Hi, @pengzhiwei2018 and @Leomrlin, this issue can be closed by #32
