### ISSUE TITLE
同类型一对多关系是否支持

### ISSUE THREAD

**Issue by aqzwy** [TuGraph-family/tugraph-analytics#25]
# 背景
异构图中存在实体A、B，两者之间存在关系e，且e基于时间存在多条不同的边作为历史记录

# 问题
查看源码后，在构建EDGE时只有SOURCE ID|  DESTINATION ID 作为边全局参数，是否边的唯一标识即为两者的一些操作作为该边
的唯一标识，当两个相同实体存在同类型多条边进入计算引擎时，如何能够有效的区分开

**Comment by Leomrlin** [comment]
这个问题可以通过指定时间戳来区分重复边，时间戳可以是真实时间，也可以为自定义的标识
DSL定义使用TIMESTAMP关键字，类似
IGraphElementWithTimeField
