### ISSUE TITLE
[k8s] add supervisor to manage worker process lifecycle

### ISSUE THREAD

**Issue by qingwen220** [TuGraph-family/tugraph-analytics#264]
This PR aims to improve the failover efficiency in k8s. 

Currently the cluster will rebuild the whole cluster by deleting all pods and recreate them when a runtime exception thrown.  This process will last serveral minutes or more when the cluster is resource limited.  

By incuring the supervisor, we could restart the worker process without releasing the pod resource.

**Comment by pengzhiwei2018** [comment]
Done in https://github.com/TuGraph-family/tugraph-analytics/pull/267
