### ISSUE TITLE
How to use Node.JS client as source / destination through `socket`?

### ISSUE THREAD

**Issue by KrishnaPG** [TuGraph-family/tugraph-analytics#271]
There seems to be support for `type='socket'` as table source and destination.

Not a java expert, and hence wondering if a Node.js client can be used a source and destination. What protocol does the `geaflow` use to communicate with the socket? It is HTTP/REST or Websocket or some other custom protocol?

```
CREATE TABLE IF NOT EXISTS tbl_source (
  text varchar
) WITH (
  type='socket',
  `geaflow.dsl.column.separator` = '#',
  `geaflow.dsl.socket.host` = 'localhost',
  `geaflow.dsl.socket.port` = 9003
);
```

Would like to be able to make the above work with Node.js client (as both source and destination table). Any example code or help would be greatly appreciated.

**Comment by QiZhang1997** [comment]
Hello, "socket connector" is only for domo demonstration and will not be used in production. We use Netty programming framework for network communication. If you want to know more about this, you can take a look at `NettyTerminalServer `,  `SocketTableSource` and `SocketTableSink`. These classes are related implementations of socket connector.

**Comment by KrishnaPG** [comment]
Thank you @QiZhang1997 Unfortunately I have zero knowledge of Java. Would like to stream the data in and out over Websocket or REST API or GRPC (from other languages, such as Node.JS). Is that possible? Any documentation or samples of connecting from websocket / REST API/ GRPC?

**Comment by KrishnaPG** [comment]
Never mind. I think there is a `jdbc` connector available. Will try to use that. However, there are few questions about its usage. Any help on those would be greatly appreciated: https://github.com/TuGraph-family/tugraph-analytics/issues/278 )
