### ISSUE TITLE
What is the SYNC frequency for DSL jdbc connector?

### ISSUE THREAD

**Issue by KrishnaPG** [TuGraph-family/tugraph-analytics#278]
Thank you for making this project available as open source. This looks very interesting. But could not find much info on how exactly the streaming works with different connectors in the DSL.

For example, what are the best practices to use `postgres`/`clickhouse` as the source/destination tables?

I am following the `detect the loops` sample from the [quickstart](https://tugraph-analytics.readthedocs.io/en/latest/docs-en/quick_start/) but want to use Postgres or Clickhouse as the table sources / destinations. 

**Question**: With table source as `postgres` or `clickhouse`, how frequently does the **geaflow** check for new data in the source table?

- Does **geaflow** keep track of last synced row from the source, or does it always scan the full table periodically?
- For example, what happens when a row that was already synced earlier by **geaflow** is changed in the source table (e.g. an old row was updated in the postgres source table) - does **geaflow** treat it as a new record and sync to the graph again or ignore it as old row?
- the quickstart uses `bin/gql_submit.sh` to run the DSL. What happens if that process gets shutdown and restarted again (with the same DSL file)? Would there be duplicates in the results table or does **geaflow**  only scan the source for new changed data (and ignores the already seen data from previous run)?

Here is the part of the DSL with JDBC as the source and destination for reference (modified from the quickstart `detect loops` example to use JDBC):
```
CREATE TABLE IF NOT EXISTS tbl_source (
  id1 bigint, 
  id2 bigint
) WITH (
	type='jdbc',
    geaflow.dsl.jdbc.driver = 'org.postgresql.Driver',
    geaflow.dsl.jdbc.url = 'jdbc:postgresql://127.0.0.1:5432/postgres',
    geaflow.dsl.jdbc.username = '',
    geaflow.dsl.jdbc.password = '',
    geaflow.dsl.jdbc.table.name = 'source_table'
);

CREATE TABLE IF NOT EXISTS tbl_result (
  a_id bigint,
  b_id bigint,
  c_id bigint,
  d_id bigint,
  a1_id bigint
) WITH (
	type='jdbc',
    geaflow.dsl.jdbc.driver = 'org.postgresql.Driver',
    geaflow.dsl.jdbc.url = 'jdbc:postgresql://127.0.0.1:5432/postgres',
    geaflow.dsl.jdbc.username = '',
    geaflow.dsl.jdbc.password = '',
    geaflow.dsl.jdbc.table.name = 'sink_table'
);
```

**Comment by Leomrlin** [comment]
@KrishnaPG Thank you for your interest in our project. GeaFlow is designed with the concept of stream-batch integration in mind, so in the DSL, we control the reading and writing of data only through the config of geaflow.dsl.window.size

In the engine, each time it scans a batch of windowSize number of data items, and if there isn't that much data available, it might block and wait, depending on the specific implementation of the Connector. Custom Connectors can be designed to return immediately, and the engine will also process the partial data returned as a batch.

Specifically for the JDBC Connector, it is currently an implementation provided by community members, and you can refer to the source code at https://github.com/TuGraph-family/tugraph-analytics/tree/master/geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc
The specific logic is to execute the following SQL statement to scan the tables in the database, "SELECT * FROM %s %s OFFSET %d ROWS FETCH NEXT (%d) ROWS ONLY;" where the offset is the offset of the last row returned from the previous scan.
This implementation may not be able to meet complex requirements, and if there are other incremental needs, you can customize the Connector logic. In any case, the engine will treat the most recent batch of scanned rows as an incremental batch for processing.

Hope this answers your questions.

**Comment by KrishnaPG** [comment]
Thank you @Leomrlin It is helpful. The `fetch` method is receiving an `Optional<Offset>` param, so I presume the **geaflow** core is sending that `offset` to the JDBC connector during the fetch call. https://github.com/TuGraph-family/tugraph-analytics/blob/27c4421e152df854cd3407ff46fc121b8652d8d0/geaflow/geaflow-dsl/geaflow-dsl-connector/geaflow-dsl-connector-jdbc/src/main/java/com/antgroup/geaflow/dsl/connector/jdbc/JDBCTableSource.java#L144

1. Does it mean the **geaflow** core is keeping track of the last read offset for each connector? 
2. What happens when old records (from already synced batches) are modified? e.g. an old record was deleted or updated. From the code the JDBC connector does not seem to process them.
 
Databases such as postgres allow `oplog` (change streams) to be observed. To track all modifications from the source table through such change streams, I guess we have to write custom adapter as you have suggested. Thanks for details. It is helpful.
