### ISSUE TITLE
SplitEx/Substr/Reverse support BinaryString as input parameter

### ISSUE THREAD

**Issue by pengzhiwei2018** [TuGraph-family/tugraph-analytics#29]
Currently GeaFlow uses BinaryString as its implementation for string, which provides better performance. However, at present, the built-in String Function uses string as the input parameter, and a direct conversion from BinaryString to String is required in the calculation phase, which has performance overhead. Implement the SplitEx/Substr/Reverse function with BinaryString as an input.

**Comment by qingfei1994** [comment]
Hi @pengzhiwei2018  may I know if I can work on this issue?  and to make it clear, is it about adding an extra implementation for SplitEx/Substr/Reverse or updating the existing funtions?
