### ISSUE TITLE
Hive connector support Hive 3.x

### ISSUE THREAD

**Issue by pengzhiwei2018** [TuGraph-family/tugraph-analytics#30]
Currently GeaFlow have support hive 2.3.x version. Please support hive 3.x version based on the **HiveVersionAdapter**.

**Comment by gsggsgggsgggs** [comment]
@pengzhiwei2018 您好，请问可以将这个问题分配给我吗？我是开源社区的新人，很渴望能够获得一个真正加入的机会，感谢！

**Comment by BUGKICKER** [comment]
@pengzhiwei2018 Hello,I have submitted a pr of this issue.Could you assigned this to me?
