### ISSUE TITLE
use Vec instead of DashMap on LabelDict.type_to_label

### ISSUE THREAD

**Issue by huang12zheng** [TuGraph-family/tugraph-analytics#343]
```rs
pub struct LabelDict {
    label_to_type: DashMap<String, u16>,
    type_to_label: DashMap<u16, String>,
    id: AtomicU16,
}
```
use `Vec` or some `lockfree Vec`, or arena instead of DashMap on `type_to_label`.

**Comment by cfsfine** [comment]
Hello! CStore(also geaflow-cstore) is a single-machine storage engine that theoretically supports multi-threaded writing on a single shard. LabelDict needs to reside in memory. When the written data has a new label, the registration interface of LabelDict needs to be called, so no matter Whether you use DashMap or other lock free structures, you need to use concurrency-safe data structures. DashMap may not necessarily perform the best here, but so far it is not a performance bottleneck. You also mentioned Arena. CStore supports cross-language calls. The premise of using pre-allocated memory is that the data is only used within CStore and does not have data transmission with the upper-layer system. But Label exist data interaction with the upper-layer system, so if use Arena, there will be life cycle problems, and copying (from the memory pool to outside the memory pool) cannot be avoided, and the performance loss will be greater.
