### ISSUE TITLE
id mapping的实现原理？

### ISSUE THREAD

**Issue by byteroll** [TuGraph-family/tugraph-analytics#356]
![image](https://github.com/TuGraph-family/tugraph-analytics/assets/15176699/943493f5-423e-4c2d-9a1d-b8c4b6afae45)

比较好奇，cstore是如何做到高效地将变长字符串映射成定长数字的？

**Comment by tanghaodong25** [comment]
@byteroll 对于较少的id, 我们用内存hashmap去影射，从1到uint64_t::max来分配id, 如果id很多，使用磁盘key-value数据库去映射。

**Comment by byteroll** [comment]
> [@byteroll](https://github.com/byteroll) 对于较少的id, 我们用内存hashmap去影射，从1到uint64_t::max来分配id, 如果id很多，使用磁盘key-value数据库去映射。

看了下源码，看起来是用rocksdb来做 string->int 映射的，每次写入点前都查询的话，我理解，L0 compaction不及时的话，mapping 查询性能受影响，从而影响写入的性能？

**Comment by tanghaodong25** [comment]
> > [@byteroll](https://github.com/byteroll) 对于较少的id, 我们用内存hashmap去影射，从1到uint64_t::max来分配id, 如果id很多，使用磁盘key-value数据库去映射。
> 
> 看了下源码，看起来是用rocksdb来做 string->int 映射的，每次写入点前都查询的话，我理解，L0 compaction不及时的话，mapping 查询性能受影响，从而影响写入的性能？

这部分会借助rocksdb block cache加速，减少直接访问磁盘的次数。
