### ISSUE TITLE
Support promethus metric report

### ISSUE THREAD

**Issue by Loognqiang** [TuGraph-family/tugraph-analytics#39]
Currently GeaFlow supports monitoring metric reporting for InfluxDB and SLF4J. In order to better support the open source ecosystem, it is necessary to support more metric reporting systems. Please implement Prometheus monitoring metric reporting.

**Comment by fanzhidongyzby** [comment]
fixed at https://github.com/TuGraph-family/tugraph-analytics/pull/270
