### ISSUE TITLE
PageRank and SSSP UDGA bug

### ISSUE THREAD

**Issue by tugraph-analytics** [TuGraph-family/tugraph-analytics#58]
**Describe the bug**
 There are bugs in the built-in implementations of the PR and SSSP algorithms of UDGA.

**Expected behavior**
Fix the implementation of the built-in PR and SSSP algorithms.

**Additional context**

**Comment by pengzhiwei2018** [comment]
Fix in https://github.com/TuGraph-family/tugraph-analytics/pull/60
