### ISSUE TITLE
Fix status to be finished when batch task completed

### ISSUE THREAD

**Issue by fanzhidongyzby** [TuGraph-family/tugraph-analytics#65]
Problem:
* Batch task status changes to be `FAILED` when completed, `FINISHED` status is expected.

Solution:
* Touch a file (named `<task-id>.finish`) when task process exits with code 0.
* Check file `<task-id>.finish` existence when task process is not present.

**Comment by pengzhiwei2018** [comment]
Fix in https://github.com/TuGraph-family/tugraph-analytics/pull/66
