### ISSUE TITLE
编译GeaFlow源码的时候报这个错

### ISSUE THREAD

**Issue by zhouzhenchen** [TuGraph-family/tugraph-analytics#8]
<img width="1470" alt="截屏2023-06-13 下午5 06 49" src="https://github.com/TuGraph-family/tugraph-analytics/assets/48077620/46d6f1e8-5d1c-4e59-8608-4bae1984accd">
<img width="1143" alt="截屏2023-06-13 下午5 06 30" src="https://github.com/TuGraph-family/tugraph-analytics/assets/48077620/db369fd0-cc9e-42d1-a427-2ae53e966341">

**Comment by Aarebecca** [comment]
看看这个 issue 里的解决方式能不能有帮助：https://github.com/TuGraph-family/tugraph-analytics/issues/1

**Comment by pengzhiwei2018** [comment]
@zhouzhenchen 能提供一下mvn截图上面的部分吗？

**Comment by zhouzhenchen** [comment]
[error.log](https://github.com/TuGraph-family/tugraph-analytics/files/11733062/error.log)
@pengzhiwei2018

**Comment by pengzhiwei2018** [comment]
@zhouzhenchen 可以先跳过test编译，不block主流程，mvn clean install -Dmaven.test.skip=true 
我们花时间重现一下你的问题，在做排查。

**Comment by pengzhiwei2018** [comment]
@zhouzhenchen 我们先试着本地重现一下这个问题
