### ISSUE TITLE
GeaFlow 快速部署建议

### ISSUE THREAD

**Issue by AK-tu** [TuGraph-family/tugraph-analytics#90]
建议在新手快速上手的时候，可以考虑多平台镜像快速使用。例如考虑一个geaflow的helm仓库，支持helm 一行命令直接部署，开箱即用。或者提供K8S生态的operator

**Comment by wuyueandrew** [comment]
非常期待

**Comment by qingwen220** [comment]
相关能力在开发中，下个版本会提供。

**Comment by fanzhidongyzby** [comment]
相关实现参考：https://github.com/TuGraph-family/tugraph-analytics/pull/241
