### ISSUE TITLE
build geaflow-console 镜像失败

### ISSUE THREAD

**Issue by wuyueandrew** [TuGraph-family/tugraph-analytics#92]
**Describe the bug**
版本 0.1
bash ./build.sh --all
构建镜像geaflow-console:0.1失败
异常输出
When using COPY with more than one source file, the destination must be a directory and end with a /

`COPY geaflow/geaflow-deploy/geaflow-assembly/target/geaflow-assembly-*.jar`

应该是build输出目录有多个`geaflow-assembly-`为前缀的jar，可以硬编码geaflow-console/Dockerfile把该行改为

`COPY geaflow/geaflow-deploy/geaflow-assembly/target/geaflow-assembly-0.1.jar`

**Comment by wuyueandrew** [comment]
另外：
1.建议新版本maven打包，我这里用的3.9.3
2.如果build环境maven 下包速度慢，build有可能失败，输出文件锁住，不确定是不是mvn -T的原因，
建议执行`bash ./build.sh --all` 前先手动执行 `mvn clean install -DskipTests -Dcheckstyle.skip`把依赖先下载到机器再`bash ./build.sh --all`

**Comment by wuyueandrew** [comment]
![image](https://github.com/TuGraph-family/tugraph-analytics/assets/28866983/793af5a4-0cae-4d0b-908a-995b627d2bab)

启动后发现问题，配置的服务器地址未生效，截图可见请求依然发到 localhost   http://127.0.0.1:8080/api/instances 

`docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 \
  -e geaflow.host=192.168.1.211 \
  -e geaflow.web.port=8888 \
  -e geaflow.gateway.port=8080 \
  -e geaflow.web.url=http://192.168.1.211:8888 \
  -e geaflow.web.gateway.url=http://192.168.1.211:8080 \
  -e geaflow.gateway.url=http://192.168.1.211:8080 \
  geaflow-console:0.1`

**Comment by pengzhiwei2018** [comment]
@652053395 看一下这个console启动报错问题

**Comment by 652053395** [comment]
> ![image](https://user-images.githubusercontent.com/28866983/253505957-793af5a4-0cae-4d0b-908a-995b627d2bab.png)
> 
> 启动后发现问题，配置的服务器地址未生效，截图可见请求依然发到 localhost http://127.0.0.1:8080/api/instances
> 
> `docker run -d --name geaflow-console -p 8080:8080 -p 8888:8888 -p 3306:3306 -p 6379:6379 -p 8086:8086 \ -e geaflow.host=192.168.1.211 \ -e geaflow.web.port=8888 \ -e geaflow.gateway.port=8080 \ -e geaflow.web.url=http://192.168.1.211:8888 \ -e geaflow.web.gateway.url=http://192.168.1.211:8080 \ -e geaflow.gateway.url=http://192.168.1.211:8080 \ geaflow-console:0.1`

可以进入容器中 查看下这两个文件吗 /opt/geaflow/config/application.properties 和 /opt/geaflow-web/packages/app/client/dist/index.html

**Comment by pengzhiwei2018** [comment]
master分支已修复
